build:
  phpunit:
    image: dangminhtruong/dockerlarav:latest
    commands:
    - cp .env.testing.example .env
    - composer install
    - php artisan config:cache
    - php artisan migrate
    - framgia-ci run --local
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  mysql_test:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  docker:
    username: octocat
    password: password
    email: dangminhtruong@gmail.com
    repo: dangminhtruong/Havana_Laravel