build:
  phpunit:
    image: dangminhtruong/dockerlarav:latest
    commands:
    - framgia-ci run --local
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  docker:
    username: octocat
    password: password
    email: xdangminhtruongx@gmail.com
    repo: dangminhtruong/Havana_Laravel
