build:
  phpunit:
    image: dangminhtruong/dockerlarav:latest
    commands:
    - composer install
    - vendor/bin/phpunit
    - framgia-ci run
  phpcs:
    image: dangminhtruong/dockerlarav:latest
    commands:
    - eslint resources/assets/js
    - phpmd app
    - phpcpd app
    - phpmetrics app
    - echo build ended!
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  docker:
    username: octoca
    password: password
    email: xdangminhtruongx@gmail.com
    repo: dangminhtruong/Havana_Laravel
